server:  
  port: ${PORT:8080}

spring:  
  application:
    name: auth-server
 
security:
  user:
    name: root
    password: password
  oauth2:
    client:
      client-id: acme
      client-secret: secret
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-test-microservices-zuul.192.168.99.100.nip.io/eureka
