server:
  port: 8080
spring:
  application:
    name: zuul-proxy-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-test-microservices-zuul.apps.crossvale-ocp.com/eureka
zuul:
    prefix: /api
    routes:
        uaa:
          path: /uaa/**
          sensitiveHeaders:
          serviceId: auth-server
        formatter:
            path: /formatter/
            sensitiveHeaders:
            serviceId: formatting-service
        sendMessage:
            path: /sendMessage/
            sensitiveHeaders:
            serviceId: scheduling-service